# Generated by Django 4.2 on 2024-04-02 00:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_order_city_remove_order_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='1024*762 thumbnail image in png,jpg or jpeg format', null=True, upload_to='vendor/inventory/product_category/banner'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='125*125 thumbnail image in png,jpg or jpeg format', null=True, upload_to='vendor/inventory/product_category/thumbnail'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
