# Generated by Django 5.0.5 on 2024-05-22 13:01

import src.administration.admins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_productdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.PositiveIntegerField(default=0, help_text='Tax  in percentage', validators=[src.administration.admins.models.discount_validator], verbose_name='Tax in %'),
        ),
    ]
