# Generated by Django 5.0.5 on 2024-05-22 18:38

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
