# Generated by Django 4.2 on 2024-04-02 00:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_productcategory_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='1024*762 thumbnail image in png,jpg or jpeg format', null=True, upload_to='vendor/inventory/product_category/banner'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='125*125 thumbnail image in png,jpg or jpeg format', null=True, upload_to='vendor/inventory/product_category/thumbnail'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
