# Generated by Django 4.2 on 2024-04-02 20:12

from django.db import migrations, models
import src.administration.admins.models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_product_height_product_length_product_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, help_text='Select Weight Like 1kg', null=True, validators=[src.administration.admins.models.positive_validator]),
        ),
    ]
