# Generated by Django 4.2 on 2024-04-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_remove_product_height_remove_product_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
    ]
