# Generated by Django 4.2 on 2024-04-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_remove_product_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.productweight'),
        ),
    ]
