# Generated by Django 4.2 on 2024-04-02 21:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_alter_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='productweight',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
