# Generated by Django 4.2 on 2024-04-20 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_productweight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.productweight'),
        ),
    ]
