# Generated by Django 4.2 on 2024-04-24 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0013_cart_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(choices=[('USA', 'USA'), ('Canada', 'Canada'), ('india', 'India')], max_length=255)),
                ('type', models.CharField(choices=[('1', 'Billing Address'), ('2', 'Shipping Address'), ('3', 'Both')], max_length=200, null=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Address',
                'verbose_name_plural': 'Order Addresses',
            },
        ),
        migrations.RemoveField(
            model_name='orderbillingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderbillingaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ordershippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordershippingaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.DeleteModel(
            name='OrderBillingAddress',
        ),
        migrations.DeleteModel(
            name='OrderShippingAddress',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
