# Generated by Django 4.2 on 2024-04-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_buyeraddress_order_address_line1_order_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeraddress',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyeraddress',
            name='phone_number',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
