# Generated by Django 4.2 on 2024-04-26 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_order_shipping_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.productweight'),
        ),
    ]
