# Generated by Django 4.2.11 on 2024-05-07 21:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0021_remove_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=250, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=250, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(default='*', null=True)),
                ('shipment_status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('cancelled', 'cancelled'), ('delivery', 'Delivery'), ('completed', 'Completed')], default='initialized', max_length=20)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('reached', models.DateTimeField(blank=True, null=True)),
                ('shipment_added', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admins.order')),
            ],
        ),
    ]
