# Generated by Django 4.2.11 on 2024-05-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0022_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(help_text='The nickname of the new pickup location', max_length=250)),
                ('name', models.CharField(help_text="The shipper's name.", max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('address_2', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('pin_code', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ShipRocketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiprocket_order_id', models.CharField(max_length=250)),
                ('shipment_id', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('status_code', models.CharField(max_length=250)),
                ('onboarding_completed_now', models.CharField(max_length=250)),
                ('awb_code', models.CharField(max_length=250)),
                ('courier_company_id', models.CharField(max_length=250)),
                ('courier_name', models.CharField(max_length=250)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.order')),
            ],
        ),
    ]
