# Generated by Django 4.2.11 on 2024-05-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0023_pickuplocation_shiprocketorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('not-selected', 'Not Selected'), ('custom', 'Custom'), ('ship_rocket', 'Ship Rocket')], default='initialized', max_length=100, null=True),
        ),
    ]
