# Generated by Django 4.2.11 on 2024-05-14 19:03

import django.core.validators
from django.db import migrations, models
import src.administration.admins.models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0024_order_shipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, message='The address must be exactly 10 characters long.'), django.core.validators.MaxLengthValidator(10, message='The address must be exactly 10 characters long.')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact',
            field=models.CharField(max_length=100, null=True, validators=[src.administration.admins.models.validate_contact]),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(100000, message='The pin code must be 6 digits.'), django.core.validators.MaxValueValidator(999999, message='The pin code must be 6 digits.')]),
        ),
    ]
