# Generated by Django 4.2.11 on 2024-05-14 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0025_alter_order_address_alter_order_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, message='The address must be exactly 10 characters long.'), django.core.validators.MaxLengthValidator(500, message='The address must be exactly 10 characters long.')]),
        ),
    ]
