# Generated by Django 4.2.11 on 2024-05-14 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0027_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10, message='The address must be at least 10 characters long.'), django.core.validators.MaxLengthValidator(300, message='The address must be at most 300 characters long.')]),
        ),
    ]
