# Generated by Django 4.2.11 on 2024-05-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0028_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiprocketorder',
            name='awb_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shiprocketorder',
            name='courier_company_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shiprocketorder',
            name='courier_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shiprocketorder',
            name='onboarding_completed_now',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shiprocketorder',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shiprocketorder',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shiprocketorder',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shiprocketorder',
            name='status_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
