# Generated by Django 4.2.11 on 2024-05-15 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0029_alter_shiprocketorder_awb_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_review',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
