# Generated by Django 4.2.11 on 2024-05-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0030_alter_product_average_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_type',
            field=models.CharField(blank=True, choices=[('not-selected', 'Not Selected'), ('custom', 'Custom'), ('ship_rocket', 'Ship Rocket')], default='not-selected', max_length=100, null=True),
        ),
    ]
