# Generated by Django 4.2.11 on 2024-05-19 19:54

from django.db import migrations, models
import django.db.models.deletion
import src.administration.admins.models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0031_alter_order_shipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, default=0, help_text='The Value of the item in cms. Must be more than 0.5.', max_digits=10, validators=[src.administration.admins.models.positive_validator])),
                ('breadth', models.DecimalField(decimal_places=2, default=0, help_text='The Value of the item in cms. Must be more than 0.5.', max_digits=10, validators=[src.administration.admins.models.positive_validator])),
                ('height', models.DecimalField(decimal_places=2, default=0, help_text='The Value of the item in cms. Must be more than 0.5.', max_digits=10, validators=[src.administration.admins.models.positive_validator])),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='The Value of the item in kgs. Must be more than 0.', max_digits=10, validators=[src.administration.admins.models.positive_validator])),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.product')),
                ('product_weight', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.weight')),
            ],
        ),
    ]
