# Generated by Django 4.2.11 on 2024-05-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0032_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product_weight',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.weight'),
            preserve_default=False,
        ),
    ]
