# Generated by Django 4.2.11 on 2024-05-19 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0034_alter_productsize_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product_weight',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.productweight'),
        ),
    ]
