# Generated by Django 4.2.11 on 2024-05-19 20:16

from django.db import migrations, models
import django.db.models.deletion
import src.administration.admins.models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0035_alter_productsize_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='breadth',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The Value of the item in cms. Must be more than 0.5.', max_digits=10, validators=[src.administration.admins.models.product_size_validator]),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The Value of the item in cms. Must be more than 0.5.', max_digits=10, validators=[src.administration.admins.models.product_size_validator]),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The Value of the item in cms. Must be more than 0.5.', max_digits=10, validators=[src.administration.admins.models.product_size_validator]),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product_weight',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='admins.productweight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsize',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The Value of the item in kgs. Must be more than 0.', max_digits=10, validators=[src.administration.admins.models.product_weight_validator]),
        ),
    ]
