# Generated by Django 4.2.11 on 2024-05-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0039_productdeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdeal',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
