# Generated by Django 4.2.11 on 2024-05-22 12:35

from django.db import migrations, models
import src.administration.admins.models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0040_alter_productdeal_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.PositiveIntegerField(default=0, help_text='Tax  in percentage', validators=[src.administration.admins.models.discount_validator], verbose_name='Tax in %'),
        ),
    ]
