# Generated by Django 4.2.11 on 2024-05-22 18:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0041_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
