# Generated by Django 4.2.11 on 2024-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0042_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('fast', 'Fast Delivery')], default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
