# Generated by Django 4.2.11 on 2024-05-26 21:00

from django.db import migrations, models
import src.administration.admins.models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0044_remove_product_tax_product_cgst_product_igst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[src.administration.admins.models.positive_validator]),
        ),
        migrations.AlterField(
            model_name='product',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[src.administration.admins.models.positive_validator]),
        ),
        migrations.AlterField(
            model_name='product',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[src.administration.admins.models.positive_validator]),
        ),
    ]
