# Generated by Django 4.2.5 on 2024-05-13 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('channel_id', models.IntegerField()),
                ('channel_name', models.CharField(max_length=255)),
                ('base_channel_code', models.CharField(max_length=10)),
                ('channel_order_id', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('pickup_location', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sla', models.CharField(max_length=50)),
                ('shipping_method', models.CharField(max_length=50)),
                ('expedited', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('status_code', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('is_international', models.IntegerField()),
                ('purpose_of_shipment', models.IntegerField()),
                ('channel_created_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('channel_order_product_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('channel_sku', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('available', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('hsn', models.CharField(max_length=50)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shipment.shipmentorder')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isd_code', models.CharField(max_length=10)),
                ('courier', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dimensions', models.CharField(max_length=50)),
                ('pickup_scheduled_date', models.DateTimeField(null=True)),
                ('pickup_token_number', models.CharField(max_length=255, null=True)),
                ('awb', models.CharField(max_length=255)),
                ('return_awb', models.CharField(max_length=255)),
                ('volumetric_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pod', models.CharField(max_length=255, null=True)),
                ('etd', models.CharField(max_length=50)),
                ('rto_delivered_date', models.DateTimeField()),
                ('delivered_date', models.DateTimeField(null=True)),
                ('etd_escalation_btn', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipment.shipmentorder')),
            ],
        ),
    ]
