# Generated by Django 4.2.5 on 2024-05-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='shipmentorder',
            name='customer_address',
            field=models.CharField(default='Pakistan', max_length=100),
            preserve_default=False,
        ),
    ]
