# Generated by Django 4.2.11 on 2024-05-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_pickuplocation_shiprocketorder_delete_channelid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='name',
            field=models.CharField(default=1, help_text="The shipper's name.", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='pickup_location',
            field=models.CharField(help_text='The nickname of the new pickup location', max_length=250),
        ),
    ]
