# Generated by Django 4.2.11 on 2024-05-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_pickuplocation_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PickupLocation',
        ),
        migrations.DeleteModel(
            name='ShipRocketOrder',
        ),
    ]
