# Generated by Django 4.2 on 2024-04-26 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='stripe_price',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExternalAccount',
        ),
        migrations.DeleteModel(
            name='OrderPayment',
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
